<?php

namespace Tests\Feature;

use App\Models\Role;
use App\Models\User;
use App\Models\Batch;
use Illuminate\Foundation\Testing\RefreshDatabase;
use Illuminate\Support\Facades\Hash;
use Tests\TestCase;

class AutoAccountCreationTest extends TestCase
{
    use RefreshDatabase;

    protected User $admin;
    protected Role $studentRole;
    protected Role $facultyRole;

    protected function setUp(): void
    {
        parent::setUp();

        $this->seed(\Database\Seeders\RoleSeeder::class);

        $adminRole = Role::where('name', 'admin')->first();
        $this->studentRole = Role::where('name', 'student')->first();
        $this->facultyRole = Role::where('name', 'faculty')->first();

        $this->admin = User::create([
            'name' => 'System Admin',
            'email' => 'admin@example.ac.in',
            'password' => bcrypt('password'),
            'role_id' => $adminRole->id,
            'phone' => '1234567890',
        ]);
    }

    /**
     * Test auto creation of student and faculty accounts when importing mentor mapping.
     */
    public function test_auto_creation_of_student_and_faculty_accounts(): void
    {
        // Students: 23IT099 (does not exist), 23IT001 (exists)
        // Faculty: Dr. Bimal Patel (does not exist), Prof. Vipul Patel (exists)
        
        // 1. Create a pre-existing student
        $existingStudent = User::create([
            'enrollment_number' => '23IT001',
            'name' => 'Existing Student',
            'email' => '23it001@charusat.edu.in',
            'department' => 'IT',
            'semester' => 6,
            'role_id' => $this->studentRole->id,
            'password' => bcrypt('password'),
            'phone' => '123456789',
        ]);

        // 2. Create a pre-existing faculty
        $existingFaculty = User::create([
            'name' => 'Prof. Vipul Patel',
            'email' => 'vipulpatel.it@charusat.ac.in',
            'faculty_id' => 'F123456',
            'role_id' => $this->facultyRole->id,
            'password' => bcrypt('password'),
            'phone' => '123456789',
        ]);

        // Preview rows generated by Excel import
        $previewRows = [
            [
                'enrollment' => '23IT099',
                'student_name' => 'New Student NineNine',
                'batch' => 'IT_2023',
                'mentor_name' => 'Dr. Bimal Patel',
                'mentor_email' => 'bimalpatel.it@charusat.ac.in',
                'status' => 'Will Create Student',
                'status_color' => 'text-indigo-600 bg-indigo-50 border border-indigo-100',
                'mentor_status' => 'Will Create Faculty',
                'student_exists' => false,
                'source_sheet' => 'Sheet1',
            ],
            [
                'enrollment' => '23IT001',
                'student_name' => 'Existing Student',
                'batch' => 'IT_2023',
                'mentor_name' => 'Prof. Vipul Patel',
                'mentor_email' => 'vipulpatel.it@charusat.ac.in',
                'status' => 'Update Assignment',
                'status_color' => 'text-green-600 bg-green-50',
                'mentor_status' => 'Existing Faculty',
                'student_exists' => true,
                'source_sheet' => 'Sheet1',
            ]
        ];

        // 3. Confirm Mapping Route
        $response = $this->actingAs($this->admin)->post(route('admin.mentor-mapping.confirm'), [
            'mappings_json' => json_encode($previewRows)
        ]);

        $response->assertRedirect(route('admin.dashboard', ['tab' => 'mentor_mapping']));
        $response->assertSessionHas('import_report');
        
        $report = session('import_report');
        $this->assertEquals(2, $report['success']); // 2 mapped students
        $this->assertEquals(1, $report['created_students']); // 1 student created
        $this->assertEquals(1, $report['created_faculty']); // 1 faculty created

        // 4. Verify Student Accounts In DB
        // Existing student should remain unchanged regarding password but guide/batch updated
        $existingStudent->refresh();
        $this->assertFalse($existingStudent->must_change_password);
        $this->assertEquals('vipulpatel.it@charusat.ac.in', $existingStudent->guide->email);

        // New student account created automatically
        $newStudent = User::where('enrollment_number', '23IT099')->first();
        $this->assertNotNull($newStudent);
        $this->assertEquals('23it099@charusat.edu.in', $newStudent->email);
        $this->assertEquals('New Student NineNine', $newStudent->name);
        $this->assertTrue($newStudent->must_change_password);
        // Default password should be enrollment number in uppercase: 23IT099
        $this->assertTrue(Hash::check('23IT099', $newStudent->password));

        // 5. Verify Faculty Accounts In DB
        // Existing faculty remains unchanged
        $existingFaculty->refresh();
        $this->assertFalse($existingFaculty->must_change_password);

        // New faculty account created automatically
        $newFaculty = User::where('email', 'bimalpatel.it@charusat.ac.in')->first();
        $this->assertNotNull($newFaculty);
        $this->assertEquals('Dr. Bimal Patel', $newFaculty->name);
        $this->assertTrue($newFaculty->must_change_password);
        // Default password should be FirstName123: Bimal123 (after stripping 'Dr.')
        $this->assertTrue(Hash::check('Bimal123', $newFaculty->password));

        // 6. Test Download Created Accounts Report
        $downloadResponse = $this->actingAs($this->admin)->get(route('admin.mentor-mapping.download-report'));
        $downloadResponse->assertStatus(200);
        $downloadResponse->assertHeader('Content-Type', 'text/csv; charset=UTF-8');
    }

    /**
     * Test force password change middleware redirection and updates.
     */
    public function test_forced_password_change_flow(): void
    {
        $newStudent = User::create([
            'enrollment_number' => '23IT099',
            'name' => 'New Student',
            'email' => '23it099@charusat.edu.in',
            'department' => 'IT',
            'semester' => 6,
            'role_id' => $this->studentRole->id,
            'password' => bcrypt('23IT099'),
            'phone' => '123456789',
            'must_change_password' => true,
        ]);

        // 1. Any request to dashboard should redirect to /password/change
        $response = $this->actingAs($newStudent)->get(route('dashboard'));
        $response->assertRedirect(route('password.change'));

        // 2. Can access password change page
        $response = $this->actingAs($newStudent)->get(route('password.change'));
        $response->assertStatus(200);
        $response->assertSee('Change Your Password');

        // 3. Attempting to change password with invalid confirm password should fail validation
        $response = $this->actingAs($newStudent)->post(route('password.change.update'), [
            'password' => 'secret123',
            'password_confirmation' => 'mismatch',
        ]);
        $response->assertSessionHasErrors('password');
        $newStudent->refresh();
        $this->assertTrue($newStudent->must_change_password);

        // 4. Successful password change updates password and resets must_change_password
        $response = $this->actingAs($newStudent)->post(route('password.change.update'), [
            'password' => 'newPassword123',
            'password_confirmation' => 'newPassword123',
        ]);
        $response->assertRedirect(route('dashboard'));
        
        $newStudent->refresh();
        $this->assertFalse($newStudent->must_change_password);
        $this->assertTrue(Hash::check('newPassword123', $newStudent->password));

        // 5. Subsequent access to dashboard works without redirection
        $response = $this->actingAs($newStudent)->get(route('dashboard'));
        $response->assertStatus(200);
    }
}
